In [1]:
import akantu as aka
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math as m
import time


In [4]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
